# tasks file for php-cli-ondrej
---
- name: mods install | install
  apt:
    name: "{{ item.dependencies | default(php_cli_ondrej_mods_dependencies[item.name]) | default([]) }}"
    state: "{{ apt_install_state | default('latest') }}"
  with_items: "{{ php_cli_ondrej_mods_present }}"
  tags:
    - php-cli-ondrej-mods-install-install
